#ifndef SAM7_H
#define SAM7_H

#ifdef __cplusplus
extern "C" {
#endif
    

/* This is fixed.  */
#define PIT_CLOCK_DIVISOR 16


#if defined (__AT91SAM7S512__)
#include "AT91SAM7S512.h"
#elif defined (__AT91SAM7S256__)
#include "AT91SAM7S256.h"
#elif defined (__AT91SAM7X256__)
#include "AT91SAM7X256.h"
#elif defined (__AT91SAM7S128__)
#include "AT91SAM7S128.h"
#elif defined (__AT91SAM7S64__)
#include "AT91SAM7S64.h"
#elif defined (__AT91SAM7S32__)
#include "AT91SAM7S32.h"
#else
#error "MCU type not defined"
#endif



/* Provide a compatibility layer with Atmel's ASF definitions.  */

#define PMC AT91C_BASE_PMC
#define SPI AT91C_BASE_SPI
#define PWM AT91C_BASE_PWMC
#define USART0 AT91C_BASE_US0
#define USART1 AT91C_BASE_US1
#define UDP AT91C_BASE_UDP
#define TC0 AT91C_BASE_TC0
#define TC1 AT91C_BASE_TC1
#define TC2 AT91C_BASE_TC2
#define PIOA AT91C_BASE_PIOA
#ifdef AT91C_BASE_PIOB
#define PIOB AT91C_BASE_PIOB
#endif
#define ADC AT91C_BASE_ADC
#define PDC_SPI AT91C_BASE_PDC_SPI
#define CKGR AT91C_BASE_CKGR
#define AIC AT91C_BASE_AIC
#define RSTC AT91C_BASE_RSTC
#define VREG AT91C_BASE_VREG
#define WDTC AT91C_BASE_WDTC
#define MC AT91C_BASE_MC

#define Pwm AT91S_PWMC_CH


#define PWMC_CH0 AT91C_BASE_PWMC_CH0
#define PWMC_CH1 AT91C_BASE_PWMC_CH1
#define PWMC_CH2 AT91C_BASE_PWMC_CH2
#define PWMC_CH3 AT91C_BASE_PWMC_CH3

#define PWM_CMR PWMC_CMR
#define PWM_SR PWMC_SR
#define PWM_ENA PWMC_ENA
#define PWM_DIS PWMC_DIS
#define PWM_ISR1 PWMC_ISR
/* Period register.  */
#define PWM_CPRD PWMC_CPRDR
/* Duty register.  */
#define PWM_CDTY PWMC_CDTYR
/* Period/duty update register.  */
#define PWM_CPRDUPD PWMC_CUPDR 
#define PWM_CDTYUPD PWMC_CUPDR
#define PwmCh_num AT91S_PWMC_CH
#define PWM_CH_NUM PWMC_CH
#define ID_PWM AT91C_ID_PWMC

#define TcChannel AT91S_TC
#define TC_BCR TCB_BCR
#define TC_BCR_SYNC AT91C_TCB_SYNC
#define TC_CCR_CLKEN AT91C_TC_CLKEN
#define TC_CCR_CLKDIS AT91C_TC_CLKDIS
#define TC_CCR_SWTRG AT91C_TC_SWTRG
#define TC_CMR_WAVSEL_UP_RC AT91C_TC_WAVESEL_UP_AUTO    
#define TC_CMR_BURST_NONE AT91C_TC_BURST_NONE
#define TC_CMR_WAVE AT91C_TC_WAVE
#define TC_CMR_ACPA_SET AT91C_TC_ACPA_SET
#define TC_CMR_ACPA_CLEAR AT91C_TC_ACPA_CLEAR
#define TC_CMR_ACPC_CLEAR AT91C_TC_ACPC_CLEAR
#define TC_CMR_ACPC_SET AT91C_TC_ACPC_SET
#define TC_CMR_CPCSTOP AT91C_TC_CPCSTOP
#define TC_CMR_ASWTRG_CLEAR AT91C_TC_ASWTRG_CLEAR
#define TC_CMR_ASWTRG_SET AT91C_TC_ASWTRG_SET
#define TC_CMR_TCCLKS_TIMER_CLOCK1 AT91C_TC_CLKS_TIMER_DIV1_CLOCK
#define ID_TC0 AT91C_ID_TC0
#define TC_IER_CPAS AT91C_TC_CPAS
#define TC_IDR_CPAS AT91C_TC_CPAS
#define TC_CMR_LDRA_RISING AT91C_TC_LDRA_RISING
#define TC_CMR_LDRB_RISING AT91C_TC_LDRB_RISING
#define TC_CMR_LDRA_FALLING AT91C_TC_LDRA_FALLING
#define TC_CMR_LDRB_FALLING AT91C_TC_LDRB_FALLING
#define TC_CMR_ABETRG AT91C_TC_ABETRG
#define TC_CMR_ETRGEDG_NONE AT91C_TC_ETRGEDG_NONE
#define TC_CMR_ETRGEDG_FALLING AT91C_TC_ETRGEDG_FALLING
#define TC_SR_COVFS AT91C_TC_COVFS
#define TC_SR_LOVRS AT91C_TC_LOVRS
#define TC_SR_LDRAS AT91C_TC_LDRAS
#define TC_SR_CLKSTA AT91C_TC_CLKSTA
#define TC_IER_LDRBS AT91C_TC_LDRBS
#define TC_IER_COVFS AT91C_TC_COVFS
#define TC_IER_LDRAS AT91C_TC_LDRAS
#define TC_SR_LDRBS AT91C_TC_LDRBS
#define TC_IDR_COVFS AT91C_TC_COVFS
#define TC_IDR_LDRAS AT91C_TC_LDRAS
#define TC_IDR_LDRBS AT91C_TC_LDRBS
#define TC_IMR_LDRAS AT91C_TC_LDRAS

#define TC_CMR_TCCLKS_TIMER_CLOCK1 AT91C_TC_CLKS_TIMER_DIV1_CLOCK
#define TC_CMR_TCCLKS_TIMER_CLOCK2 AT91C_TC_CLKS_TIMER_DIV2_CLOCK
#define TC_CMR_TCCLKS_TIMER_CLOCK3 AT91C_TC_CLKS_TIMER_DIV3_CLOCK
#define TC_CMR_TCCLKS_TIMER_CLOCK4 AT91C_TC_CLKS_TIMER_DIV4_CLOCK
#define ID_TC0 AT91C_ID_TC0
#define ID_TC1 AT91C_ID_TC1
#define ID_TC2 AT91C_ID_TC2

#define ADC_CR_SWRST AT91C_ADC_SWRST
#define ADC_CR_START AT91C_ADC_START
#define ADC_MR_SLEEP AT91C_ADC_SLEEP
#define ADC_MR_LOWRES AT91C_ADC_LOWRES

#define US_TXEMPTY AT91C_US_TXEMPTY
#define US_RXRDY AT91C_US_RXRDY
#define US_TXRDY AT91C_US_TXRDY

#define ID_USART0 AT91C_ID_US0
#define ID_USART1 AT91C_ID_US1

#define US_CSR_RXRDY AT91C_US_RXRDY
#define US_CSR_TXRDY AT91C_US_TXRDY
#define US_CSR_TXEMPTY AT91C_US_TXEMPTY

#define US_CR_RSTRX AT91C_US_RSTRX
#define US_CR_RSTTX AT91C_US_RSTTX
#define US_CR_RXDIS AT91C_US_RXDIS
#define US_CR_TXDIS AT91C_US_TXDIS
#define US_CR_RXEN AT91C_US_RXEN
#define US_CR_TXEN AT91C_US_TXEN

#define US_MR_USART_MODE_NORMAL AT91C_US_USMODE_NORMAL
#define US_MR_CHRL_8_BIT AT91C_US_CHRL_8_BITS
#define US_MR_PAR_NO AT91C_US_PAR_NONE
#define US_MR_NBSTOP_1_BIT AT91C_US_NBSTOP_1_BIT

#define ID_IRQ0 AT91C_ID_IRQ0
#define ID_IRQ1 AT91C_ID_IRQ1


#define ID_SPI AT91C_ID_SPI
#define ID_SPI1 AT91C_ID_SPI1

#define Spi AT91S_SPI

#define SPI_MR_PS AT91C_SPI_PS_VARIABLE
#define SPI_CR_SWRST AT91C_SPI_SWRST
#define SPI_CR_SPIEN AT91C_SPI_SPIEN
#define SPI_CR_SPIDIS AT91C_SPI_SPIDIS
#define SPI_MR_MSTR AT91C_SPI_MSTR
#define SPI_MR_MODFDIS AT91C_SPI_MODFDIS
#define SPI_SR_RDRF AT91C_SPI_RDRF
#define SPI_SR_ENDTX AT91C_SPI_ENDTX
#define SPI_SR_ENDRX AT91C_SPI_ENDRX

#define Udp AT91PS_UDP

#define ID_UDP AT91C_ID_UDP

#define UDP_IER_SOFINT AT91C_UDP_SOFINT
#define UDP_ISR_ENDBUSRES AT91C_UDP_ENDBUSRES

#define UDP_TXVC_TXVDIS AT91C_UDP_TXVDIS
#define UDP_IER_RXSUSP AT91C_UDP_RXSUSP
#define UDP_IER_WAKEUP AT91C_UDP_WAKEUP
#define UDP_IER_RXRSM AT91C_UDP_RXRSM
#define UDP_RST_EP UDP_RSTEP
#define UDP_GLB_STAT UDP_GLBSTATE
#define UDP_CSR_EPTYPE_CTRL AT91C_UDP_EPTYPE_CTRL
#define UDP_CSR_EPTYPE_BULK_OUT AT91C_UDP_EPTYPE_BULK_OUT
#define UDP_CSR_RX_DATA_BK0 AT91C_UDP_RX_DATA_BK0
#define UDP_CSR_RX_DATA_BK1 AT91C_UDP_RX_DATA_BK1
#define UDP_CSR_EPTYPE_BULK_IN AT91C_UDP_EPTYPE_BULK_IN
#define UDP_CSR_EPEDS AT91C_UDP_EPEDS
#define UDP_CSR_TXCOMP AT91C_UDP_TXCOMP
#define UDP_CSR_TXPKTRDY AT91C_UDP_TXPKTRDY
#define UDP_CSR_DIR AT91C_UDP_DIR
#define UDP_CSR_RXSETUP AT91C_UDP_RXSETUP
#define UDP_CSR_FORCESTALL AT91C_UDP_FORCESTALL
#define UDP_CSR_STALLSENT AT91C_UDP_STALLSENT
#define UDP_FADDR_FEN AT91C_UDP_FEN
#define UDP_GLB_STAT_FADDEN AT91C_UDP_FADDEN
#define UDP_GLB_STAT_CONFG AT91C_UDP_CONFG
#define UDP_IER_EP0INT AT91C_UDP_EPINT0

#define UDP_ICR_RXSUSP AT91C_UDP_RXSUSP
#define UDP_ICR_WAKEUP AT91C_UDP_WAKEUP
#define UDP_ICR_RXRSM AT91C_UDP_RXRSM

#define UDP_CSR_EPTYPE_Msk AT91C_UDP_EPTYPE

#define PMC_SCDR_UDP AT91C_PMC_UDP
#define PMC_SCER_UDP AT91C_PMC_UDP

#define ADC_ISR_DRDY AT91C_ADC_DRDY
#define ADC_ISR ADC_SR



#ifdef __cplusplus
}
#endif    
#endif

